api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "discount-free-shipping-loyalty-tiers"
type = "function"
uid = "d13767d2-991c-40be-3861-a8d59b9ecee32f45bd12"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

[extensions.ui]
handle = "ui-discount-free-shipping-loyalty-tiers"
[discount.metafields.app.free-shipping-loyalty-tiers]
type = "json"
name = "Free Shipping Loyalty Tiers configuration"
description = "Free Shipping Loyalty Tiers discount function."
access.admin = "merchant_read_write"
access.storefront = "none"

